### ISSUE TITLE
ParamValidationError for imageId create batch entities

### ISSUE THREAD

**Issue by whistler** [awslabs/aws-batch-helpers#2]
When I run the create-batch-entities.py script to create batch entities, I get the following validation error. I have tried passing in the imageId with and without the 'ami-' prefix with the same outcome. I am using Python 2.7.12 and boto-2.48.0.

```python create-batch-entities.py --subnets "..." --security-groups "..." --key-pair "..." --image-id "ami-c5c7e2be" --instance-role "..." --service-role "..."
Traceback (most recent call last):
  File "create-batch-entities.py", line 167, in <module>
    main()
  File "create-batch-entities.py", line 158, in main
    keyPair=keyPair)
  File "create-batch-entities.py", line 56, in create_compute_environment
    'instanceRole': instanceRole
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 513, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 566, in _convert_to_request_dict
    api_params, operation_model)
  File "/Library/Python/2.7/site-packages/botocore/validate.py", line 270, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in computeResources: "imageId", must be one of: type, minvCpus, maxvCpus, desiredvCpus, instanceTypes, subnets, securityGroupIds, ec2KeyPair, instanceRole, tags, bidPercentage, spotIamFleetRole```

**Comment by kiukA9** [comment]
Looks like it is failing on a client-side parameter check. In this case the batch service model need an update. Try updating boto to pull the latest model (you should have the one from the link below).

https://github.com/boto/botocore/blob/develop/botocore/data/batch/2016-08-10/service-2.json

**Comment by whistler** [comment]
Upgrading to the latest version of `boto3` fixes this.
